cc_library(
    name = "domain_carousel",
    hdrs = ["domain_carousel.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib:deque",
        "//lib:string",
        "//lib:utils",
    ],
)
