cc_library(
    name = "PostPractice",
    srcs = ["PostingList.cpp"],
    hdrs = ["PostingList.h"],
    visibility = ["//visibility:public"],   # <-- add this
    deps = [
        "//lib:vector",
        "//lib:string",
        "//lib:unordered_map",
        "//lib:priority_queue",
        "//lib:utils",
    ],
)